index:
    path: /
    controller: App\Controller\HomeController::index

indexFilterPrice:
    path: /filterprice
    controller: App\Controller\HomeController::indexFilterPrice

indexFilterName:
    path: /filterbyname
    controller: App\Controller\HomeController::indexFilterName

indexFilterCategory:
    path: /filterbyCategory
    controller: App\Controller\HomeController::indexFilterCategory

register:
    path: /register
    controller: App\Controller\HomeController::register
    methods: get

registerPost:
    path: /register
    controller: App\Controller\UserController::registerPost
    methods: post

login:
    path: /login
    controller: App\Controller\HomeController::login
    methods: get

loginPost:
    path: /login
    controller: App\Controller\UserController::loginPost
    methods: post

product:
    path: /product/{id}
    controller: App\Controller\ProductController::product

addProduct:
    path: /panier/add/{id}
    controller: App\Controller\CartController::addProduct

addQuantity:
    path: /panier/addquantity/{id}
    controller: App\Controller\CartController::addQuantity

deleteQuantity:
    path: /panier/deleltequantity/{id}
    controller: App\Controller\CartController::deleteQuantity

removeProduct:
    path: /panier/remove/{id}
    controller: App\Controller\CartController::RemoveProduct
    

profil:
    path: /profil/{id}
    controller: App\Controller\UserController::profil

payment:
    path: /payment
    controller: App\Controller\OrderController::payment

order:
    path: /panier
    controller: App\Controller\CartController::panier
    

history:
    path: /history
    controller: App\Controller\OrderController::history

details_product:
    path: /product{id}
    controller: App\Controller\ProductController::detailsbis


    



