index:
    path: /
    controller: App\Controller\HomeController::index

register:
    path: /register
    controller: App\Controller\HomeController::register
    methods: get

registerPost:
    path: /register
    controller: App\Controller\UserController::registerPost
    methods: post

login:
    path: /login
    controller: App\Controller\HomeController::login

product:
    path: /product/{id}
    controller: App\Controller\ProductController::product

profil:
    path: /profil/{id}
    controller: App\Controller\UserController::profil

payment:
    path: /payment
    controller: App\Controller\OrderController::payment

order:
    path: /checkout
    controller: App\Controller\OrderController::order

history:
    path: /history
    controller: App\Controller\OrderController::history
